version: "3.9"

volumes:
  frontend: {}

services:
  frontend:
    build: 
      context: ../frontend
      dockerfile: _build/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - frontend:/usr/src/app

  webserver:
    build: nginx
    ports:
      - 8081:80
    volumes:
      - frontend:/usr/src/app
    depends_on:
      - frontend
